#index:
#    path: /
#    controller: App\Controller\DefaultController::index
dashboard:
    path: /dashboard
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\DashboardController::index
entry:
    path: /entry
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\EntryController::index